// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package test.org.attnetwork.proto.pb.msg;

public final class ProtocolBufferTest {
  private ProtocolBufferTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleUserMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ExampleUserMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>float score = 4;</code>
     * @return The score.
     */
    float getScore();

    /**
     * <code>string phone = 5;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 5;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> 
        getContactsList();
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getContacts(int index);
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    java.util.List<? extends test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.ExampleUserMsg}
   */
  public static final class ExampleUserMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ExampleUserMsg)
      ExampleUserMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExampleUserMsg.newBuilder() to construct.
    private ExampleUserMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExampleUserMsg() {
      firstName_ = "";
      lastName_ = "";
      phone_ = "";
      contacts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExampleUserMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExampleUserMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 37: {

              score_ = input.readFloat();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contacts_ = new java.util.ArrayList<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              contacts_.add(
                  input.readMessage(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.class, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 4;
    private float score_;
    /**
     * <code>float score = 4;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 5;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 5;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACTS_FIELD_NUMBER = 6;
    private java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> contacts_;
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    @java.lang.Override
    public java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    @java.lang.Override
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    @java.lang.Override
    public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
     */
    @java.lang.Override
    public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (score_ != 0F) {
        output.writeFloat(4, score_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phone_);
      }
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(6, contacts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (score_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, score_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, phone_);
      }
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, contacts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg)) {
        return super.equals(obj);
      }
      test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg other = (test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (java.lang.Float.floatToIntBits(getScore())
          != java.lang.Float.floatToIntBits(
              other.getScore())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getContactsList()
          .equals(other.getContactsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore());
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ExampleUserMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ExampleUserMsg)
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.class, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.Builder.class);
      }

      // Construct using test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContactsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        firstName_ = "";

        lastName_ = "";

        score_ = 0F;

        phone_ = "";

        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserMsg_descriptor;
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg getDefaultInstanceForType() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.getDefaultInstance();
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg build() {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg buildPartial() {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg result = new test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.score_ = score_;
        result.phone_ = phone_;
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg) {
          return mergeFrom((test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg other) {
        if (other == test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getScore() != 0F) {
          setScore(other.getScore());
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>float score = 4;</code>
       * @return The score.
       */
      @java.lang.Override
      public float getScore() {
        return score_;
      }
      /**
       * <code>float score = 4;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(float value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 5;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 5;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 5;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 5;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contacts_ = new java.util.ArrayList<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg>(contacts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder setContacts(
          int index, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder setContacts(
          int index, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder addContacts(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder addContacts(
          int index, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder addContacts(
          test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder addContacts(
          int index, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder getContactsBuilder(
          int index) {
        return getContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public java.util.List<? extends test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder addContactsBuilder() {
        return getContactsFieldBuilder().addBuilder(
            test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder addContactsBuilder(
          int index) {
        return getContactsFieldBuilder().addBuilder(
            index, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.ExampleUserContactMsg contacts = 6;</code>
       */
      public java.util.List<test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder> 
           getContactsBuilderList() {
        return getContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder> 
          getContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ExampleUserMsg)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ExampleUserMsg)
    private static final test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg();
    }

    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleUserMsg>
        PARSER = new com.google.protobuf.AbstractParser<ExampleUserMsg>() {
      @java.lang.Override
      public ExampleUserMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExampleUserMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExampleUserMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleUserMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExampleUserContactMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ExampleUserContactMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string remark = 2;</code>
     * @return The remark.
     */
    java.lang.String getRemark();
    /**
     * <code>string remark = 2;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();
  }
  /**
   * Protobuf type {@code tutorial.ExampleUserContactMsg}
   */
  public static final class ExampleUserContactMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ExampleUserContactMsg)
      ExampleUserContactMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExampleUserContactMsg.newBuilder() to construct.
    private ExampleUserContactMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExampleUserContactMsg() {
      remark_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExampleUserContactMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExampleUserContactMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserContactMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserContactMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.class, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int REMARK_FIELD_NUMBER = 2;
    private volatile java.lang.Object remark_;
    /**
     * <code>string remark = 2;</code>
     * @return The remark.
     */
    @java.lang.Override
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>string remark = 2;</code>
     * @return The bytes for remark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, remark_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, remark_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg)) {
        return super.equals(obj);
      }
      test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg other = (test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ExampleUserContactMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ExampleUserContactMsg)
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserContactMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserContactMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.class, test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.Builder.class);
      }

      // Construct using test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        remark_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.internal_static_tutorial_ExampleUserContactMsg_descriptor;
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getDefaultInstanceForType() {
        return test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.getDefaultInstance();
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg build() {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg buildPartial() {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg result = new test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg(this);
        result.id_ = id_;
        result.remark_ = remark_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg) {
          return mergeFrom((test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg other) {
        if (other == test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object remark_ = "";
      /**
       * <code>string remark = 2;</code>
       * @return The remark.
       */
      public java.lang.String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string remark = 2;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        java.lang.Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remark = 2;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 2;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ExampleUserContactMsg)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ExampleUserContactMsg)
    private static final test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg();
    }

    public static test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleUserContactMsg>
        PARSER = new com.google.protobuf.AbstractParser<ExampleUserContactMsg>() {
      @java.lang.Override
      public ExampleUserContactMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExampleUserContactMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExampleUserContactMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleUserContactMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.org.attnetwork.proto.pb.msg.ProtocolBufferTest.ExampleUserContactMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ExampleUserMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ExampleUserMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ExampleUserContactMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ExampleUserContactMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010tutorial\"\222\001\n\016ExampleUserMs" +
      "g\022\n\n\002id\030\001 \001(\003\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010last" +
      "Name\030\003 \001(\t\022\r\n\005score\030\004 \001(\002\022\r\n\005phone\030\005 \001(\t" +
      "\0221\n\010contacts\030\006 \003(\0132\037.tutorial.ExampleUse" +
      "rContactMsg\"3\n\025ExampleUserContactMsg\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006remark\030\002 \001(\tB6\n test.org.att" +
      "network.proto.pb.msgB\022ProtocolBufferTest" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_ExampleUserMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ExampleUserMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ExampleUserMsg_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Score", "Phone", "Contacts", });
    internal_static_tutorial_ExampleUserContactMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_ExampleUserContactMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ExampleUserContactMsg_descriptor,
        new java.lang.String[] { "Id", "Remark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
